extends: existence
message: "Don't use rich formatting in headings (bold, italic, monospace)."
nonword: true
level: error
scope: raw
tokens:
  - ^={1,6} .*?\*{1,2}(.*?)\*{1,2}
  - ^={1,6} .*?_(.*?)_.*
  - ^={1,6} .*?\x60(.*?)\x60.*
